# https://circleci.com/docs/2.0/

version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11-stretch

    working_directory: /go/src/github.com/shisa-platform/core

    steps:
      - checkout
      - run:
          shell: /bin/bash
          name: go fmt
          command: |
            ! gofmt -l $(find . -path ./vendor -prune -o  -type f -name '*.go' -print) 2>&1 | read
      - run: go vet ./...
      - run: make test
      - run: sbin/codecov

  mdl:
    docker:
      - image: rsrchboy/mdl
    steps:
      - checkout
      - run:
          name: Validate Markdown
          command: |
            mdl $(find . -path ./vendor -prune -o -type f -name '*.md' -print)

workflows:
  version: 2
  build_release:
    jobs:
      - mdl
      - build
