# This Dockerfile is used as a base for each of the examples
FROM alpine:3.7

COPY ./ /root/go/src/github.com/percolate/shisa

WORKDIR /root/go/src/github.com/percolate/shisa

RUN apk --no-cache --update add bash go curl git musl-dev
