// generated by "charlatan -output=./consulresolver_charlatan.go consulResolver".  DO NOT EDIT.

package sd

import consul "github.com/hashicorp/consul/api"
import "reflect"

// consulResolverServiceInvocation represents a single call of FakeconsulResolver.Service
type consulResolverServiceInvocation struct {
	Parameters struct {
		Service     string
		Tag         string
		PassingOnly bool
		Q           *consul.QueryOptions
	}
	Results struct {
		Ident1 []*consul.ServiceEntry
		Ident2 *consul.QueryMeta
		Ident3 error
	}
}

// consulResolverTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type consulResolverTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
FakeconsulResolver is a mock implementation of consulResolver for testing.
Use it in your tests as in this example:

	package example

	func TestWithconsulResolver(t *testing.T) {
		f := &sd.FakeconsulResolver{
			ServiceHook: func(service string, tag string, passingOnly bool, q *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error) {
				// ensure parameters meet expections, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakeService ...
		f.AssertServiceCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakeService.
*/
type FakeconsulResolver struct {
	ServiceHook func(string, string, bool, *consul.QueryOptions) ([]*consul.ServiceEntry, *consul.QueryMeta, error)

	ServiceCalls []*consulResolverServiceInvocation
}

// NewFakeconsulResolverDefaultPanic returns an instance of FakeconsulResolver with all hooks configured to panic
func NewFakeconsulResolverDefaultPanic() *FakeconsulResolver {
	return &FakeconsulResolver{
		ServiceHook: func(string, string, bool, *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error) {
			panic("Unexpected call to consulResolver.Service")
		},
	}
}

// NewFakeconsulResolverDefaultFatal returns an instance of FakeconsulResolver with all hooks configured to call t.Fatal
func NewFakeconsulResolverDefaultFatal(t consulResolverTestingT) *FakeconsulResolver {
	return &FakeconsulResolver{
		ServiceHook: func(string, string, bool, *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error) {
			t.Fatal("Unexpected call to consulResolver.Service")
			return
		},
	}
}

// NewFakeconsulResolverDefaultError returns an instance of FakeconsulResolver with all hooks configured to call t.Error
func NewFakeconsulResolverDefaultError(t consulResolverTestingT) *FakeconsulResolver {
	return &FakeconsulResolver{
		ServiceHook: func(string, string, bool, *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error) {
			t.Error("Unexpected call to consulResolver.Service")
			return
		},
	}
}

func (f *FakeconsulResolver) Reset() {
	f.ServiceCalls = []*consulResolverServiceInvocation{}
}

func (_f1 *FakeconsulResolver) Service(service string, tag string, passingOnly bool, q *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error) {
	invocation := new(consulResolverServiceInvocation)
	_f1.ServiceCalls = append(_f1.ServiceCalls, invocation)

	invocation.Parameters.Service = service
	invocation.Parameters.Tag = tag
	invocation.Parameters.PassingOnly = passingOnly
	invocation.Parameters.Q = q

	ident1, ident2, ident3 = _f1.ServiceHook(service, tag, passingOnly, q)

	invocation.Results.Ident1 = ident1
	invocation.Results.Ident2 = ident2
	invocation.Results.Ident3 = ident3

	return
}

// ServiceCalled returns true if FakeconsulResolver.Service was called
func (f *FakeconsulResolver) ServiceCalled() bool {
	return len(f.ServiceCalls) != 0
}

// AssertServiceCalled calls t.Error if FakeconsulResolver.Service was not called
func (f *FakeconsulResolver) AssertServiceCalled(t consulResolverTestingT) {
	t.Helper()
	if len(f.ServiceCalls) == 0 {
		t.Error("FakeconsulResolver.Service not called, expected at least one")
	}
}

// ServiceNotCalled returns true if FakeconsulResolver.Service was not called
func (f *FakeconsulResolver) ServiceNotCalled() bool {
	return len(f.ServiceCalls) == 0
}

// AssertServiceNotCalled calls t.Error if FakeconsulResolver.Service was called
func (f *FakeconsulResolver) AssertServiceNotCalled(t consulResolverTestingT) {
	t.Helper()
	if len(f.ServiceCalls) != 0 {
		t.Error("FakeconsulResolver.Service called, expected none")
	}
}

// ServiceCalledOnce returns true if FakeconsulResolver.Service was called exactly once
func (f *FakeconsulResolver) ServiceCalledOnce() bool {
	return len(f.ServiceCalls) == 1
}

// AssertServiceCalledOnce calls t.Error if FakeconsulResolver.Service was not called exactly once
func (f *FakeconsulResolver) AssertServiceCalledOnce(t consulResolverTestingT) {
	t.Helper()
	if len(f.ServiceCalls) != 1 {
		t.Errorf("FakeconsulResolver.Service called %d times, expected 1", len(f.ServiceCalls))
	}
}

// ServiceCalledN returns true if FakeconsulResolver.Service was called at least n times
func (f *FakeconsulResolver) ServiceCalledN(n int) bool {
	return len(f.ServiceCalls) >= n
}

// AssertServiceCalledN calls t.Error if FakeconsulResolver.Service was called less than n times
func (f *FakeconsulResolver) AssertServiceCalledN(t consulResolverTestingT, n int) {
	t.Helper()
	if len(f.ServiceCalls) < n {
		t.Errorf("FakeconsulResolver.Service called %d times, expected >= %d", len(f.ServiceCalls), n)
	}
}

// ServiceCalledWith returns true if FakeconsulResolver.Service was called with the given values
func (_f2 *FakeconsulResolver) ServiceCalledWith(service string, tag string, passingOnly bool, q *consul.QueryOptions) (found bool) {
	for _, call := range _f2.ServiceCalls {
		if reflect.DeepEqual(call.Parameters.Service, service) && reflect.DeepEqual(call.Parameters.Tag, tag) && reflect.DeepEqual(call.Parameters.PassingOnly, passingOnly) && reflect.DeepEqual(call.Parameters.Q, q) {
			found = true
			break
		}
	}

	return
}

// AssertServiceCalledWith calls t.Error if FakeconsulResolver.Service was not called with the given values
func (_f3 *FakeconsulResolver) AssertServiceCalledWith(t consulResolverTestingT, service string, tag string, passingOnly bool, q *consul.QueryOptions) {
	t.Helper()
	var found bool
	for _, call := range _f3.ServiceCalls {
		if reflect.DeepEqual(call.Parameters.Service, service) && reflect.DeepEqual(call.Parameters.Tag, tag) && reflect.DeepEqual(call.Parameters.PassingOnly, passingOnly) && reflect.DeepEqual(call.Parameters.Q, q) {
			found = true
			break
		}
	}

	if !found {
		t.Error("FakeconsulResolver.Service not called with expected parameters")
	}
}

// ServiceCalledOnceWith returns true if FakeconsulResolver.Service was called exactly once with the given values
func (_f4 *FakeconsulResolver) ServiceCalledOnceWith(service string, tag string, passingOnly bool, q *consul.QueryOptions) bool {
	var count int
	for _, call := range _f4.ServiceCalls {
		if reflect.DeepEqual(call.Parameters.Service, service) && reflect.DeepEqual(call.Parameters.Tag, tag) && reflect.DeepEqual(call.Parameters.PassingOnly, passingOnly) && reflect.DeepEqual(call.Parameters.Q, q) {
			count++
		}
	}

	return count == 1
}

// AssertServiceCalledOnceWith calls t.Error if FakeconsulResolver.Service was not called exactly once with the given values
func (_f5 *FakeconsulResolver) AssertServiceCalledOnceWith(t consulResolverTestingT, service string, tag string, passingOnly bool, q *consul.QueryOptions) {
	t.Helper()
	var count int
	for _, call := range _f5.ServiceCalls {
		if reflect.DeepEqual(call.Parameters.Service, service) && reflect.DeepEqual(call.Parameters.Tag, tag) && reflect.DeepEqual(call.Parameters.PassingOnly, passingOnly) && reflect.DeepEqual(call.Parameters.Q, q) {
			count++
		}
	}

	if count != 1 {
		t.Errorf("FakeconsulResolver.Service called %d times with expected parameters, expected one", count)
	}
}

// ServiceResultsForCall returns the result values for the first call to FakeconsulResolver.Service with the given values
func (_f6 *FakeconsulResolver) ServiceResultsForCall(service string, tag string, passingOnly bool, q *consul.QueryOptions) (ident1 []*consul.ServiceEntry, ident2 *consul.QueryMeta, ident3 error, found bool) {
	for _, call := range _f6.ServiceCalls {
		if reflect.DeepEqual(call.Parameters.Service, service) && reflect.DeepEqual(call.Parameters.Tag, tag) && reflect.DeepEqual(call.Parameters.PassingOnly, passingOnly) && reflect.DeepEqual(call.Parameters.Q, q) {
			ident1 = call.Results.Ident1
			ident2 = call.Results.Ident2
			ident3 = call.Results.Ident3
			found = true
			break
		}
	}

	return
}
