// generated by "charlatan -output=./consulselfer_charlatan.go selfer".  DO NOT EDIT.

package env

// selferSelfInvocation represents a single call of Fakeselfer.Self
type selferSelfInvocation struct {
	Results struct {
		Ident1 map[string]map[string]interface{}
		Ident2 error
	}
}

// selferTestingT represents the methods of "testing".T used by charlatan Fakes.  It avoids importing the testing package.
type selferTestingT interface {
	Error(...interface{})
	Errorf(string, ...interface{})
	Fatal(...interface{})
	Helper()
}

/*
Fakeselfer is a mock implementation of selfer for testing.
Use it in your tests as in this example:

	package example

	func TestWithselfer(t *testing.T) {
		f := &env.Fakeselfer{
			SelfHook: func() (ident1 map[string]map[string]interface{}, ident2 error) {
				// ensure parameters meet expections, signal errors using t, etc
				return
			},
		}

		// test code goes here ...

		// assert state of FakeSelf ...
		f.AssertSelfCalledOnce(t)
	}

Create anonymous function implementations for only those interface methods that
should be called in the code under test.  This will force a panic if any
unexpected calls are made to FakeSelf.
*/
type Fakeselfer struct {
	SelfHook func() (map[string]map[string]interface{}, error)

	SelfCalls []*selferSelfInvocation
}

// NewFakeselferDefaultPanic returns an instance of Fakeselfer with all hooks configured to panic
func NewFakeselferDefaultPanic() *Fakeselfer {
	return &Fakeselfer{
		SelfHook: func() (ident1 map[string]map[string]interface{}, ident2 error) {
			panic("Unexpected call to selfer.Self")
		},
	}
}

// NewFakeselferDefaultFatal returns an instance of Fakeselfer with all hooks configured to call t.Fatal
func NewFakeselferDefaultFatal(t selferTestingT) *Fakeselfer {
	return &Fakeselfer{
		SelfHook: func() (ident1 map[string]map[string]interface{}, ident2 error) {
			t.Fatal("Unexpected call to selfer.Self")
			return
		},
	}
}

// NewFakeselferDefaultError returns an instance of Fakeselfer with all hooks configured to call t.Error
func NewFakeselferDefaultError(t selferTestingT) *Fakeselfer {
	return &Fakeselfer{
		SelfHook: func() (ident1 map[string]map[string]interface{}, ident2 error) {
			t.Error("Unexpected call to selfer.Self")
			return
		},
	}
}

func (f *Fakeselfer) Reset() {
	f.SelfCalls = []*selferSelfInvocation{}
}

func (_f1 *Fakeselfer) Self() (ident1 map[string]map[string]interface{}, ident2 error) {
	if _f1.SelfHook == nil {
		panic("selfer.Self() called but Fakeselfer.SelfHook is nil")
	}

	invocation := new(selferSelfInvocation)
	_f1.SelfCalls = append(_f1.SelfCalls, invocation)

	ident1, ident2 = _f1.SelfHook()

	invocation.Results.Ident1 = ident1
	invocation.Results.Ident2 = ident2

	return
}

// SetSelfStub configures selfer.Self to always return the given values
func (_f2 *Fakeselfer) SetSelfStub(ident1 map[string]map[string]interface{}, ident2 error) {
	_f2.SelfHook = func() (map[string]map[string]interface{}, error) {
		return ident1, ident2
	}
}

// SelfCalled returns true if Fakeselfer.Self was called
func (f *Fakeselfer) SelfCalled() bool {
	return len(f.SelfCalls) != 0
}

// AssertSelfCalled calls t.Error if Fakeselfer.Self was not called
func (f *Fakeselfer) AssertSelfCalled(t selferTestingT) {
	t.Helper()
	if len(f.SelfCalls) == 0 {
		t.Error("Fakeselfer.Self not called, expected at least one")
	}
}

// SelfNotCalled returns true if Fakeselfer.Self was not called
func (f *Fakeselfer) SelfNotCalled() bool {
	return len(f.SelfCalls) == 0
}

// AssertSelfNotCalled calls t.Error if Fakeselfer.Self was called
func (f *Fakeselfer) AssertSelfNotCalled(t selferTestingT) {
	t.Helper()
	if len(f.SelfCalls) != 0 {
		t.Error("Fakeselfer.Self called, expected none")
	}
}

// SelfCalledOnce returns true if Fakeselfer.Self was called exactly once
func (f *Fakeselfer) SelfCalledOnce() bool {
	return len(f.SelfCalls) == 1
}

// AssertSelfCalledOnce calls t.Error if Fakeselfer.Self was not called exactly once
func (f *Fakeselfer) AssertSelfCalledOnce(t selferTestingT) {
	t.Helper()
	if len(f.SelfCalls) != 1 {
		t.Errorf("Fakeselfer.Self called %d times, expected 1", len(f.SelfCalls))
	}
}

// SelfCalledN returns true if Fakeselfer.Self was called at least n times
func (f *Fakeselfer) SelfCalledN(n int) bool {
	return len(f.SelfCalls) >= n
}

// AssertSelfCalledN calls t.Error if Fakeselfer.Self was called less than n times
func (f *Fakeselfer) AssertSelfCalledN(t selferTestingT, n int) {
	t.Helper()
	if len(f.SelfCalls) < n {
		t.Errorf("Fakeselfer.Self called %d times, expected >= %d", len(f.SelfCalls), n)
	}
}
